name: Database

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: postgres:9.6
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      TZ: "America/Los_Angeles"
      HSQLDB_DATABASE_URL: "jdbc:hsqldb:file:target/hsqldb;shutdown=true"
      HSQLDB_DATABASE_USER: SA
      HSQLDB_DATABASE_PASSWORD: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Copy Maven settings
        run: cp ./travis/maven-settings.xml $HOME/.m2/settings.xml

      - name: Set POM version with build number
        run: sed -i "s/-SNAPSHOT/-build-${{ github.run_number }}/" pom.xml

      - name: Authenticate to Google Cloud using Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          project_id: 'som-rit-infrastructure-prod'
          workload_identity_provider: 'projects/294515190965/locations/global/workloadIdentityPools/github/providers/susom-github'

      - name: Configure Maven to use gcloud credentials for Artifact Registry
        run: |
          gcloud auth application-default login
          gcloud auth application-default set-quota-project som-rit-infrastructure-prod
          gcloud config set artifacts/repository public-maven

      - name: Run Tests
        run: |
          mvn -e -Dfailsafe.rerunFailingTestsCount=3 -Dmaven.javadoc.skip=true \
          -Dhsqldb.database.url=${{ env.HSQLDB_DATABASE_URL }} \
          -Dhsqldb.database.user=${{ env.HSQLDB_DATABASE_USER }} \
          -Dhsqldb.database.password=${{ env.HSQLDB_DATABASE_PASSWORD }} \
          -Pcoverage,hsqldb verify &&
          bash test-postgres.sh &&
          bash test-sqlserver.sh &&
          bash test-oracle.sh

      - name: Print Surefire reports on failure
        if: failure()
        run: |
          echo "\n=== SUREFIRE REPORTS ===\n"
          for F in target/surefire-reports/*.txt; do echo $F; cat $F; echo; done

  deploy_snapshots:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Copy Maven settings
        run: cp ./travis/maven-settings.xml $HOME/.m2/settings.xml

      - name: Set POM version with build number
        run: sed -i "s/-SNAPSHOT/-build-${{ github.run_number }}/" pom.xml

      - name: Authenticate to Google Cloud using Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          project_id: 'som-rit-infrastructure-prod'
          workload_identity_provider: 'projects/294515190965/locations/global/workloadIdentityPools/github/providers/susom-github'

      - name: Configure Maven to use gcloud credentials for Artifact Registry
        run: |
          gcloud auth application-default login
          gcloud auth application-default set-quota-project som-rit-infrastructure-prod
          gcloud config set artifacts/repository public-maven

      - name: Deploy snapshots
        run: mvn --batch-mode -e -DskipTests=true deploy