name: database

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run Maven Tests
      run: |
        mvn -e -Dfailsafe.rerunFailingTestsCount=3 -Dmaven.javadoc.skip=true \
        "-Dhsqldb.database.url=jdbc:hsqldb:file:target/hsqldb;shutdown=true" \
        -Dhsqldb.database.user=SA -Dhsqldb.database.password= \
        -Pcoverage,hsqldb verify
        bash test-postgres.sh
        bash test-sqlserver.sh
        bash test-oracle.sh
        mvn -e org.jacoco:jacoco-maven-plugin:report

    - name: Print Surefire reports on failure
      if: failure()
      run: |
        echo "\n=== SUREFIRE REPORTS ===\n"
        for F in target/surefire-reports/*.txt; do echo $F; cat $F; echo; done

  deploy_snapshots:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Deploy Snapshots
      run: |
        mvn --batch-mode -e -DskipTests=true deploy